name       : stellarium
version    : 0.15.0
release    : 4
source     :
    - http://netassist.dl.sourceforge.net/project/stellarium/Stellarium-sources/0.15.0/stellarium-0.15.0.tar.gz : 74d0e3a69fcbaf1c6278f601a44497fd3e9f2de7dfa11a60197d3afb68288746
license    : GPL-2.0
component  : education
summary    : Free open source planetarium application
description: |
    Stellarium is a free open source planetarium for your computer. It shows a realistic sky in 3D, just like what you see with the naked eye, binoculars or a telescope.
    It is being used in planetarium projectors. Just set your coordinates and go.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Gui)
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
