name       : stellarium
version    : 0.15.2
release    : 6
source     :
    - https://netassist.dl.sourceforge.net/project/stellarium/Stellarium-sources/0.15.2/stellarium-0.15.2.tar.gz : 6943c088fa7675164168d3f627491131df60fc6377eac7224e1086271091dda6
license    : GPL-2.0
component  : education
summary    : Free open source planetarium application
description: |
    Stellarium is a free open source planetarium for your computer. It shows a realistic sky in 3D, just like what you see with the naked eye, binoculars or a telescope.
    It is being used in planetarium projectors. Just set your coordinates and go.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Gui)
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5Script)
    - pkgconfig(Qt5SerialPort)
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
