name       : stellarium
version    : 0.22.0
release    : 26
source     :
    - https://github.com/Stellarium/stellarium/releases/download/v0.22.0/stellarium-0.22.0.tar.gz : 0b4dc23cf9054b5e76cd9bc5ad68e172eb221999e90af37e93667d04fe78c885
homepage   : https://stellarium.org/
license    : GPL-2.0-or-later
component  : office.scientific
summary    : Free open source planetarium application
description: |
    Stellarium is a free open source planetarium for your computer. It shows a realistic sky in 3D, just like what you see with the naked eye, binoculars or a telescope.
    It is being used in planetarium projectors. Just set your coordinates and go.
builddeps  :
    - pkgconfig(Qt5Charts)
    - pkgconfig(Qt5Gui)
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5Script)
    - pkgconfig(Qt5SerialPort)
    - pkgconfig(Qt5Positioning)
rundeps    :
    - dejavu-fonts-ttf
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install

    # use system fonts
    rm $installdir/usr/share/stellarium/data/DejaVuSans{Mono,}.ttf
    ln -s /usr/share/fonts/truetype/dejavu/DejaVuSans.ttf $installdir/usr/share/stellarium/data/DejaVuSans.ttf
    ln -s /usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf $installdir/usr/share/stellarium/data/DejaVuSansMono.ttf
