name       : stellarium
version    : 0.16.0
release    : 7
source     :
    - https://nchc.dl.sourceforge.net/project/stellarium/Stellarium-sources/0.16.0/stellarium-0.16.0.tar.gz : 2835c4aa22c1b64edbd17b174a23e4ed23654cd09e12f3573709f44843913dcf
license    : GPL-2.0
component  : education
summary    : Free open source planetarium application
description: |
    Stellarium is a free open source planetarium for your computer. It shows a realistic sky in 3D, just like what you see with the naked eye, binoculars or a telescope.
    It is being used in planetarium projectors. Just set your coordinates and go.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Gui)
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5Script)
    - pkgconfig(Qt5SerialPort)
    - pkgconfig(Qt5Positioning)
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
