name       : stellarium
version    : 0.17.0
release    : 10
source     :
    - https://github.com/Stellarium/stellarium/releases/download/v0.17.0/stellarium-0.17.0.tar.gz : cc21e2daf5433b0b99c6e81101171b47da7b278b6c3e4e433cde4555b41bcb34
license    : GPL-2.0
component  : office.scientific
summary    : Free open source planetarium application
description: |
    Stellarium is a free open source planetarium for your computer. It shows a realistic sky in 3D, just like what you see with the naked eye, binoculars or a telescope.
    It is being used in planetarium projectors. Just set your coordinates and go.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Gui)
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5Script)
    - pkgconfig(Qt5SerialPort)
    - pkgconfig(Qt5Positioning)
rundeps    :
    - dejavu-fonts-ttf
setup      : |
    %cmake . -DENABLE_TESTING=true
build      : |
    %make
install    : |
    %make_install

    # use system fonts
    rm $installdir/usr/share/stellarium/data/DejaVuSans{Mono,}.ttf
    ln -s /usr/share/fonts/truetype/dejavu/DejaVuSans.ttf $installdir/usr/share/stellarium/data/DejaVuSans.ttf
    ln -s /usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf $installdir/usr/share/stellarium/data/DejaVuSansMono.ttf
check      : |
    %make test
